Mallang-Trip/Web

src/pages/SignupPage/PersonalInfo/index.jsx
src/pages/SignupPage/index.jsx

closed #61 
- 개인정보 보안 취약점 개선을 위한 회원가입 API 요청 내용 수정

회원가입 API 요청 내용 수정

---

src/pages/SignupPage/PersonalInfo/index.jsx
src/pages/SignupPage/index.jsx

closed #61 
- 수정된 회원가입 로직을 배포합니다.

수정된 회원가입 로직 배포

---

index.html
src/components/Credit/index.jsx

closed #69 
- 결제 기능을 테스트 환경에서 라이브 환경으로 전환했습니다.
- 이제부터 결제는 실결제로 이루어집니다.
- 결제는 개발 환경이 아닌 배포 환경에서만 가능합니다.

feat: 결제 라이브 환경 적용

---

src/api/income.js
src/assets/svg/income-more-info.svg
src/components/Header/index.jsx
src/components/PartyIconBox/index.jsx
src/pages/DriverIncomePage/IncomeInfo/Account/index.jsx
src/pages/DriverIncomePage/IncomeInfo/MonthlyIncome/index.jsx
src/pages/DriverIncomePage/IncomeInfo/index.jsx
src/pages/DriverIncomePage/IncomeTable/Body/index.jsx
src/pages/DriverIncomePage/IncomeTable/Head/index.jsx
src/pages/DriverIncomePage/IncomeTable/index.jsx
src/pages/DriverIncomePage/Title/index.jsx
src/pages/DriverIncomePage/index.jsx
src/pages/LandingPage/KakaoButton/index.jsx
src/pages/LandingPage/NewPartyButton/index.jsx
src/pages/LandingPage/index.jsx
src/pages/MyMenuPage/Menu/index.jsx
src/router/index.jsx
tailwind.config.js

* #78 
* 드라이버 수익 관리 페이지를 완성했습니다.
* 드라이버는 본인의 수익 내역을 확인할 수 있습니다.
* 기획 팀의 요구 사항 변경으로 인해, 송금확인증 발급 기능은 제거되었습니다.

드라이버 수익 관리

---

src/components/PlaceMap/DestinationModal/index.jsx
src/components/PlaceMap/NoDataModal/index.jsx
src/pages/AdminPage/Management/Place/DestinationModal/index.jsx
src/pages/DestinationPage/PlaceInfoBox/PlaceInfoTitle/index.jsx
src/pages/DriverCoursePage/index.jsx
src/pages/MyHeartPage/HeartItem/index.jsx
src/pages/PartyPage/EditAgreement/index.jsx

- 코스 제안 취소 버튼 위치 수정
- 여행지 방문수 -> 조회수 변경
- 여행지 검색 결과 멘트 수정
- 드라이버 파티 코스 수정 예외 처리

변경된 기획 요구사항 반영 및 오류 수정

---

src/components/CourseMap/index.jsx
src/components/Footer/Company/index.jsx
src/pages/LandingPage/DriverHome/DriverTab/index.jsx
src/pages/LandingPage/DriverHome/PartyList/NoParty/index.jsx
src/pages/LandingPage/DriverHome/PartyList/index.jsx
src/pages/LandingPage/DriverHome/index.jsx
src/pages/LandingPage/DriverMenu/index.jsx
src/pages/LandingPage/PartyFilter/index.jsx
src/pages/LandingPage/PartyList/index.jsx
src/pages/LandingPage/index.jsx

- 기획 팀의 요구 사항에 따라, 드라이버 전용 랜딩 페이지를 수정했습니다.
- 관리자 계정으로 말랑톡 문의를 할 수 없도록 예외 처리를 추가했습니다.

드라이버 전용 랜딩 페이지 수정

---

src/components/CourseMap/index.jsx
src/components/PlaceMap/DestinationModal/index.jsx
src/components/PlaceMap/MapBox/index.jsx
src/components/PlaceMap/NewPlaceModal/index.jsx
src/components/ProfileModal/ProfileInfo/index.jsx
src/components/ProfileModal/index.jsx
src/pages/AdminPage/Management/Place/DestinationModal/index.jsx
src/pages/AdminPage/Management/Place/NewPlaceModal/index.jsx
src/pages/AdminPage/Management/Place/PlaceMap/index.jsx
src/pages/AdminPage/User/DriverInfo/DriverTable/Body/index.jsx
src/pages/AdminPage/User/DriverInfo/DriverTable/Head/index.jsx
src/pages/DestinationPage/PlaceInfoBox/PlaceInfoTitle/index.jsx
src/pages/DriverApplyPage/Accout/index.jsx
src/pages/DriverApplyPage/RegionList/Region/index.jsx
src/pages/DriverApplyPage/index.jsx
src/pages/DriverCoursePage/index.jsx
src/pages/MyProfilePage/DriverProfile/Price/PriceModal/index.jsx
src/pages/NewPartyPage/Edit/index.jsx
src/pages/NewPartyPage/Reservation/index.jsx
src/pages/PartyPage/PartyMember/index.jsx
src/pages/PartyPage/index.jsx

- #89 
- 드라이버 전용 홈에 '새로운 파티 승인 대기' 명칭 변경
- 드라이버 파티 코스 설정 과정에 파티 코스 가격 및 수수료 표시
- 지도 확대/축소 성능 최적화
- 로그인 필수 페이지 라우팅 옵션 수정
- 관리자 페이지 내 드라이버 회원 정보에 활동 지역 추가
- 내 정보에 결제 수단 관리 기능 추가
- 예약 취소 모달 텍스트 줄바꿈 수정
- 고객센터 페이지 상담 컴포넌트 위치 수정
- 드라이버 가격 설정 모달 타이틀 수정

변경된 기획 요구 사항 반영

---

src/components/CourseMap/index.jsx
src/pages/LandingPage/KakaoButton/index.jsx
src/pages/LandingPage/NewPartyButton/index.jsx
src/pages/NewPartyPage/index.jsx
src/pages/PartyPage/JoinButton/index.jsx
src/pages/PartyPage/PartyMember/index.jsx
src/pages/PartyPage/index.jsx
src/utils/data.js

- 드라이버 파티 가입, 생성 제한
- 파티 드라이버 프로필 이름 변경 - OOO 드라이버
- 파티 status type 추가

파티 관련 수정 사항 반영

---

src/api/card.js
src/components/Header/index.jsx
src/pages/MyMenuPage/Menu/index.jsx
src/pages/MyPaymentListPage/PaymentTable/Body/index.jsx
src/pages/MyPaymentListPage/PaymentTable/Head/index.jsx
src/pages/MyPaymentListPage/PaymentTable/index.jsx
src/pages/MyPaymentListPage/index.jsx
src/pages/MyReservationPage/ReservationList/ReservationYear/index.jsx
src/router/index.jsx

- 나의 결제/환불 내역 페이지 UI 개발
- 나의 결제/환불 내역 페이지 API 연동
- 결제/환불 영수증 확인

나의 결제/환불 내역

---

src/pages/AdminPage/Management/Feedback/FeedbackItem/index.jsx
src/pages/AdminPage/Management/Feedback/Tab/index.jsx
src/pages/AdminPage/Management/Feedback/index.jsx
src/pages/AdminPage/Notification/Noti-mail/Tab/index.jsx
src/pages/AdminPage/Notification/Noti-mail/TableBody/NotiMailsItem/index.jsx
src/pages/AdminPage/Notification/Noti-mail/TableBody/index.jsx
src/pages/AdminPage/Notification/Noti-mail/TableHead/index.jsx
src/pages/AdminPage/Notification/Noti-mail/WriteEmail/index.jsx
src/pages/AdminPage/Notification/Noti-mail/index.jsx
src/pages/AdminPage/User/AdminAuth/AddUserModal/AdminUserItem/index.jsx
src/pages/AdminPage/User/AdminAuth/AddUserModal/index.jsx
src/pages/AdminPage/User/AdminAuth/TableBody/AdminAuthItem/index.jsx
src/pages/AdminPage/User/AdminAuth/TableBody/index.jsx
src/pages/AdminPage/User/AdminAuth/TableHead/index.jsx
src/pages/AdminPage/User/AdminAuth/index.jsx
src/pages/AdminPage/index.jsx

관리자 페이지 UI 및 모달 구현
- 관리 > 피드백 페이지
- 관리자 권한 부여 페이지
- 약관 및 전체 메일 알림 페이지

관리자 피드백 & 권한 부여 & 약관 메일 알림 UI

---

src/components/Credit/index.jsx

feat : 결제 수단 등록 컴포넌트 아래에 잔액 부족시 카드 등록 불가 메세지 추가

---

src/components/CourseMap/index.jsx

closed #107 
#107 
파티 페이지 지도 내에서 마커 아래 장소 이름 대신 코스 순서를 표기

fix: 맵 코스 마커 아래 이름 대신 숫자

---

package-lock.json
package.json
src/pages/AdminPage/User/DriverInfo/DriverDetail/index.jsx
src/pages/AdminPage/User/DriverRegistration/DriverDetail/Vehicle/index.jsx
src/pages/DriverApplyPage/CarInfo/index.jsx
src/pages/DriverApplyPage/index.jsx
src/pages/DriverProfilePage/CarInfo/index.jsx
src/pages/DriverProfilePage/index.jsx
src/pages/MyProfilePage/DriverProfile/Vehicle/ImageInput/index.jsx
src/pages/MyProfilePage/DriverProfile/Vehicle/VehicleImage/index.jsx
src/pages/MyProfilePage/DriverProfile/Vehicle/index.jsx
src/pages/MyProfilePage/DriverProfile/index.jsx
src/pages/MyProfilePage/index.jsx

closed #109 
드라이버 차량 사진 여러 장 API 등록 관련 변경점에 해당하는 코드 부분을 우선적으로 수정 완료했습니다.

feat : 드라이버 차량 사진 여러장 업로드 가능하도록 API 변경점 수정

---

package-lock.json
package.json
src/components/BottomNav/index.jsx
tailwind.config.js

style : bottom nav iOS에서 겹치는 문제 해결

---

src/components/CourseList/CourseItem/index.jsx
src/components/PWAInstall/index.jsx
src/hoc/Auth.jsx
src/pages/DriverProfilePage/CarInfo/index.jsx
src/pages/DriverProfilePage/index.jsx
src/pages/LoginPage/LoginForm/index.jsx
src/pages/NewPartyPage/index.jsx

- #115 
- 필수 로그인 페이지 redirect 로직을 수정했습니다.
- 뒤로가기 기능이 동작하지 않는 문제가 해결되었습니다.
- PWA 앱 설치 안내가 모바일 기기에서만 등장하도록 수정했습니다.

필수 로그인 페이지 redirect 로직 수정

---

package-lock.json
package.json
src/api/region.js
src/components/BottomNav/index.jsx
src/components/CourseList/CourseItem/index.jsx
src/components/PWAInstall/index.jsx
src/components/PlaceMap/MapBox/index.jsx
src/components/PlaceMap/SearchBox/index.jsx
src/components/PlaceMap/index.jsx
src/hoc/Auth.jsx
src/pages/AdminPage/Management/Place/PlaceMap/index.jsx
src/pages/AdminPage/Management/Place/SearchBar/index.jsx
src/pages/AdminPage/Management/Place/index.jsx
src/pages/AdminPage/User/DriverInfo/DriverDetail/index.jsx
src/pages/AdminPage/User/DriverRegistration/DriverDetail/Vehicle/index.jsx
src/pages/DriverApplyPage/CarInfo/index.jsx
src/pages/DriverApplyPage/index.jsx
src/pages/DriverProfilePage/CarInfo/index.jsx
src/pages/DriverProfilePage/index.jsx
src/pages/LoginPage/LoginForm/index.jsx
src/pages/MyProfilePage/DriverProfile/Vehicle/ImageInput/index.jsx
src/pages/MyProfilePage/DriverProfile/Vehicle/VehicleImage/index.jsx
src/pages/MyProfilePage/DriverProfile/Vehicle/index.jsx
src/pages/MyProfilePage/DriverProfile/index.jsx
src/pages/MyProfilePage/index.jsx
src/pages/NewPartyPage/Course/index.jsx
src/pages/NewPartyPage/MemberAndDate/Member/index.jsx
src/pages/NewPartyPage/MemberAndDate/PageButton/index.jsx
src/pages/NewPartyPage/index.jsx
tailwind.config.js

- #116 
- #118 
- #119 
- #120 
- #122

지도 렌더링 최적화 & redirect 로직 수정 & 드라이버 차량 이미지

---

src/pages/SignupPage/PersonalInfo/index.jsx

closed #126 
회원가입 인증번호 전송 버튼 클릭 시 20세 미만 일 경우 "회원가입은 20세 이상부터 가능합니다" 오버레이 띄우기
만 14세 제한 useEffect 삭제

회원가입 나이 제한

---

src/pages/AdminPage/User/DriverInfo/DriverDetail/index.jsx
src/pages/AdminPage/User/DriverRegistration/DriverDetail/Vehicle/index.jsx
src/pages/AdminPage/User/DriverRegistration/DriverList/DriverItem/index.jsx
src/pages/DriverApplyPage/CarInfo/CarImage/index.jsx
src/pages/DriverApplyPage/CarInfo/index.jsx
src/pages/DriverApplyPage/index.jsx
src/pages/DriverProfilePage/index.jsx
src/pages/MyProfilePage/DriverProfile/index.jsx

closed #129 
드라이버 등록하기 화면에서 드라이버 차량 입력이 안되던 오류 수정을 진행했습니다.
또한, 드라이버 등록 컴포넌트의 너비보다 입력한 사진들의 너비가 더 클 경우에 스크롤 바가 생기도록 하였고,
등록한 사진 위에 커서를 올리면 사용자가 사진을 삭제할 수 있게 적용했습니다.

fix  : 드라이버 차량 사진 여러개 업로드

---

src/pages/PartyPage/PartyIntro/index.jsx
src/pages/PartyPage/index.jsx

파티 페이지 에서 파티 개설한 여행자가 작성한 파티 소개글을 다른 사람들이 볼 수 있도록 "파티 소개" 항목 추가

feat: 파티 페이지 파티 소개 항목 추가

---

src/pages/MyHeartPage/HeartItem/index.jsx
src/pages/MyHeartPage/index.jsx

closed #132 
사진이 없는 파티/장소를 찜했을 때, 엑박이 뜨는 현상 삭제
디자인 팀에서 아무 사진도 없을 경우 그냥 회색으로 처리해달라는 요청이 있어서 그냥 alt를 삭제하는 방향으로 해결했습니다.

feat : 사진이 없을 때 alt 삭제

---

src/pages/NewPartyPage/Atom/CreateModal/index.jsx
src/pages/NewPartyPage/Edit/PriceList/PriceButton/index.jsx
src/pages/NewPartyPage/Edit/PriceList/index.jsx
src/pages/NewPartyPage/Edit/index.jsx
src/pages/NewPartyPage/Reservation/index.jsx
src/pages/NewPartyPage/index.jsx

파티 코스 수정 시 드라이버가 설정해 놓은 시간 별 비용 선택지 추가

feat: 코스 수정 시 드라이버가 설정한 시간 별 비용 선택지 추가

---

src/pages/DriverProfilePage/index.jsx
src/pages/NewPartyPage/Atom/CreateModal/index.jsx
src/pages/NewPartyPage/Edit/PriceList/PriceButton/index.jsx
src/pages/NewPartyPage/Edit/PriceList/index.jsx
src/pages/NewPartyPage/Edit/index.jsx
src/pages/NewPartyPage/index.jsx

closed #141 
member param을 0에서 1로 변경하여 보내줌

fix: 드라이버 프로필에서 코스 선택 후 코스 수정이 불가한 이슈 해결

---

src/pages/DriverCoursePage/CourseDnD/index.jsx
src/pages/NewPartyPage/Atom/CreateModal/index.jsx
src/pages/NewPartyPage/Edit/index.jsx
src/pages/PartyPage/CourseDnD/index.jsx
src/pages/PartyPage/EditModal/index.jsx
src/pages/PartyPage/index.jsx

- #143 
- 코스 수정 과정에서 파티 이름, 출발 시간을 변경할 수 있도록 기능을 추가했습니다.
- 기존 파티의 코스를 수정할 때와 새로운 파티를 만들 때 모두 적용 완료했습니다.

코스 수정시 파티 이름, 출발 시간 변경

---

src/pages/AdminPage/User/DriverRegistration/DriverDetail/Vehicle/index.jsx
src/pages/DriverApplyPage/CarInfo/index.jsx
src/pages/DriverApplyPage/index.jsx
src/pages/MyProfilePage/DriverProfile/Vehicle/index.jsx

- #146 
- 드라이버 등록시 차량 번호를 받습니다.
- 드라이버 프로필에서 차량 번호를 관리합니다. (드라이버, 관리자)

드라이버 차량 번호 관리

---

src/components/ProfileModal/ButtonBox/ButtonList/BlockModal/index.jsx
src/components/ProfileModal/ButtonBox/ButtonList/index.jsx
src/pages/AdminPage/User/DriverRegistration/DriverDetail/Vehicle/index.jsx
src/pages/DriverApplyPage/CarInfo/index.jsx
src/pages/DriverApplyPage/index.jsx
src/pages/MyProfilePage/DriverProfile/Vehicle/index.jsx
src/pages/NotifyPage/NotifyList/index.jsx
src/pages/PartyPage/EditModal/index.jsx
src/pages/PartyPage/JoinModal/index.jsx

- #148 
- 유저 차단 코멘트 수정
- 신고 및 제재 중인 사용자는 파티 가입 불가능 처리

유저 차단, 신고 관련 기능 변경

---

src/components/Comment/AddComment/index.jsx
src/components/Comment/CommentList/Comment/index.jsx

closed #149 
- 평점 5점 초과시 모달창
- 평점 및 댓글 입력 여부에 따른 댓글 전송 버튼 비활성화 / 활성화

feature : 댓글 작성 시 예외처리

---

src/pages/AdminPage/User/UserInfo/UserTable/Body/index.jsx
src/pages/AdminPage/User/UserInfo/UserTable/Head/index.jsx

- #158 
- 기획, 마케팅 팀 요구 사항에 따라, 관리자가 여행자의 이름을 관리할 수 있도록 추가했습니다.

관리자 여행자 회원 이름 관리

---

src/components/BottomNav/index.jsx
src/components/CourseList/index.jsx
src/components/Footer/Company/index.jsx
src/components/Header/index.jsx
src/components/ProfileModal/ButtonBox/AdminButtonList/index.jsx
src/pages/AdminPage/CustomerService/Report/ReportContent/MallangTalkModal/index.jsx
src/pages/AdminPage/CustomerService/Report/ReportContent/index.jsx
src/pages/AdminPage/Payment/Party/index.jsx
src/pages/AdminPage/User/DriverRegistration/DriverDetail/AcceptButton/index.jsx
src/pages/CommunityPage/ArticleDetail/ArticleBody/index.jsx
src/pages/CommunityPage/ArticleDetail/ArticleComment/CommentItem/ReplyItem/index.jsx
src/pages/CommunityPage/ArticleDetail/ArticleComment/CommentItem/index.jsx
src/pages/DriverProfilePage/index.jsx
src/pages/IntroPage/ServiceList/index.jsx
src/pages/NewPartyPage/Course/index.jsx
src/pages/NewPartyPage/Edit/index.jsx
src/pages/NewPartyPage/MemberAndDate/PageButton/index.jsx
src/pages/NewPartyPage/Region/index.jsx
src/pages/NewPartyPage/Reservation/index.jsx
src/pages/NewPartyPage/index.jsx
src/pages/TalkPage/TalkList/NewTalkButton/NewTalkModal/NewTalkInfo/index.jsx
src/pages/TalkPage/TalkList/NewTalkButton/NewTalkModal/index.jsx
src/pages/TalkPage/TalkList/NoTalkList/index.jsx
src/pages/TalkPage/TalkList/index.jsx
src/pages/TalkPage/TalkRoom/TalkMenu/ExitButton/ExitCheckModal/index.jsx
src/pages/TalkPage/TalkRoom/TalkMenu/ExitButton/index.jsx
src/pages/TalkPage/TalkRoom/TalkMenu/MenuHead/index.jsx

말랑톡 -> 말랑챗 으로 수정
'~톡하기'의 경우 '~채팅하기'로 수정
코드 상 영문 표기된 mallangTalk 등은 수정하지 않음

fix: 말랑톡 > 말랑챗 이름 수정

---

src/pages/PartyPage/index.jsx

파티 페이지 타인 비공개 처리 오류 수정

---

src/components/Header/index.jsx
src/pages/CommunityPage/SearchBar/index.jsx
src/pages/CommunityPage/index.jsx
src/pages/CommunitySearchPage/index.jsx
src/pages/SearchPlacePage/index.jsx

closed #164 
메인 페이지의 검색창을 삭제했습니다.

feat : 메인 페이지 검색창 삭제

---

public/firebase-messaging-sw.js
src/api/notification.js
src/components/PushNotification/index.jsx
src/pages/NotifyPage/NotifyList/index.jsx
src/redux/modules/userSlice.js
src/utils/axios.js

- #168 
- 로그인한 모든 기기로 푸시 알림을 받을 수 있도록 처리
- 말랑챗 푸시 알림 추가
- 푸시 알림을 확인하면, 해당 페이지로 바로 이동하도록 처리

푸시 알림 기능 개선

---

src/pages/NewPartyPage/index.jsx

- #172 
- 새로운 파티 코스 만들기 오류 수정 (여행자)

새로운 파티 만들기 오류 수정

---

src/pages/DriverProfilePage/index.jsx
src/pages/NewPartyPage/Driver/DriverProfile/index.jsx
src/pages/NewPartyPage/Driver/index.jsx
src/pages/NewPartyPage/index.jsx

새로운 파티 만들어 제안하기 로직 수정

---

src/pages/CommunityPage/ArticleDetail/ArticleBody/index.jsx

closed #179 
- 커뮤니티 페이지에서 프로필 클릭 시 프로필 오버레이를 적용했습니다.
- 백엔드에서의 api 수정을 통해 'ㅇㅇㅇ 드라이버'라는 이름으로의 수정을 확인했습니다.

feat : 프로필 클릭시 프로필 오버레이 적용

---

.github/workflows/deploy_production.yml
package-lock.json
package.json
src/App.jsx
src/hooks/useGoogleTagManager.jsx

- Google Tag Manager를 적용했습니다.
- 배포된 운영 환경에서만 동작하도록 처리했습니다.
- 개발 환경, 개발 서버에서는 동작하지 않습니다.

Google Tag Manager 적용

---

src/components/Comment/CommentList/Comment/index.jsx
src/components/Comment/CommentList/index.jsx
src/pages/TalkPage/TalkRoom/TalkMenu/ExitButton/index.jsx
src/pages/TalkPage/TalkRoom/TalkMenu/MenuMembers/Member/index.jsx

- 말랑챗 탈퇴 오류를 해결했습니다.
- 댓글 삭제 확인 모달을 추가했습니다.

말랑챗 탈퇴 오류 & 댓글 삭제 확인

---

index.html
public/firebase-messaging-sw.js

- 푸시 알림 UX를 개선했습니다.
- 푸시 알림을 누를 때, 브라우저 탭에 이미 열려 있으면 해당 탭으로 바로 이동합니다.
- 푸시 알림을 누를 때, 브라우저 탭에 이미 열려 있지 않으면, 새로운 탭으로 바로 이동합니다.
- 두 경우에, 관련된 페이지로 바로 이동합니다.

푸시 알림 UX 개선

---

src/pages/PartyPage/JoinGreeting/index.jsx

- closed #193 
오른쪽 아래 radius가 깨지던 현상을 위 사진처럼 해결했습니다.

style : comment radius 깨짐 해결

---

src/pages/TalkPage/TalkRoom/TalkMenu/MenuMembers/Member/index.jsx
src/pages/TalkPage/TalkRoom/TalkRoomForm/index.jsx
src/pages/TalkPage/TalkRoom/index.jsx

- #195 
- 파티 오픈 말랑챗에 다른 유저 초대
- 차단한 유저와 개인 채팅 불가능
- 파티원은 강퇴 버튼 숨기기

말랑챗 디테일 기능 추가

---

index.html
public/firebase-messaging-sw.js
src/components/ProfileModal/ButtonBox/ButtonList/BlockModal/index.jsx
src/pages/TalkPage/TalkList/NewTalkButton/NewTalkModal/index.jsx
src/pages/TalkPage/TalkRoom/ImageModal/index.jsx
src/pages/TalkPage/TalkRoom/TalkRoomForm/index.jsx

- #194 
- #196 
- 말랑챗 기능 오류 수정
- 이미지 선택 오류 수정
- 말랑챗 강퇴/차단 기능 개선
- comment radius UI 오류 수정

말랑챗 기능 오류 수정

---

src/pages/CommunityPage/ArticleDetail/ArticleBody/index.jsx
src/pages/NewPartyPage/MemberAndDate/PageButton/index.jsx
src/pages/NewPartyPage/MemberAndDate/PartyDate/index.jsx
src/pages/NewPartyPage/index.jsx

- 커뮤니티 게시글 신고 기능 추가
- 새로운 파티 만들기 페이지 로직 수정

새로운 파티 만들기 로직 수정 & 커뮤니티 게시글 신고

---

src/api/card.js
src/pages/AdminPage/Management/Region/RegionList/EditFormModal/index.jsx
src/pages/AdminPage/Management/Region/RegionList/NewRegion/FormModal/index.jsx
src/pages/AdminPage/Management/Region/RegionList/RegionItem/index.jsx
src/pages/LandingPage/PartyList/PartyBox/index.jsx
src/pages/LandingPage/PartyList/index.jsx
src/pages/MyReservationPage/ReservationList/ReservationYear/index.jsx
src/pages/NewPartyPage/Region/index.jsx
src/pages/PartyPage/CreditInfo/index.jsx
src/pages/PartyPage/index.jsx

- 랜딩 페이지 스크롤 버그 수정
- 파티 리스트 스타일 수정 (padding)
- 새로운 파티 만들기 지역 안뜨는 오류 수정
- 여행 지역 도 단위 추가
- 결제 실패시 재결제 시도 기능 추가

여행 지역 도 단위 관리 & 결제 재시도 기능 추가

---

index.html

구글 애널리틱스 테스트를 위해 빠르게 추가해 PR 올림
이후 SPA 이슈 적용은 feature branch에서 작업예정

feat : index.html head태그에 google analytics 태그 추가

---

src/pages/NewPartyPage/Region/index.jsx

홈파티 > '가고 싶은 여행지를 찾아요'의 여행지 목록 중 '그 외' 아이템을 마지막으로 보내기

fix: 가고 싶은 여행지 목록 중 '그 외' 최하단으로 sort

---

.github/workflows/deploy_production.yml
index.html
package-lock.json
package.json
src/App.jsx
src/components/RouteChangeTracker/index.jsx
src/pages/NewPartyPage/Region/index.jsx

* 기존 html에 삽입된 메타픽셀 데이터를 리액트에 맞게 수정
* 구글 애널리틱스 GA4 관련 로직 및 페이지별 데이터 트래킹 로직 추가
RouteChangeTracker라는 컴포넌트에서 GA4와 Meta Pixel관련 트래킹을 같이 처리
참고 링크 :  
* https://3d-yeju.tistory.com/71

데이터 트래킹 관련 GA4, Meta Pixel 로직 추가

---

src/pages/AdminPage/Management/Region/RegionList/EditFormModal/index.jsx
src/pages/AdminPage/Management/Region/RegionList/NewRegion/FormModal/index.jsx
src/pages/AdminPage/Management/Region/RegionList/RegionItem/index.jsx

* 지역 도 단위 추가된 로직 롤백
기존 새로운 지역 추가
변경된 새로운 지역 추가
기존지역 편집
변경된 지역 편집
delete해야되는데 feat으로 커밋해버렸네요

어드민 페이지 가고싶은 지역 탭 추가/편집 모달창에서 도 지역 삭제

---

.github/workflows/deploy_production.yml
index.html
src/App.jsx
src/components/RouteChangeTracker/index.jsx

- #207 
- 관리자 가고 싶은 지역 관리 - 도 지역 삭제
- 지역 `name` 하나로 통일

관리자 가고 싶은 지역 관리 도 지역 삭제

---

src/pages/AdminPage/KPI/Container/index.jsx
src/pages/AdminPage/KPI/index.jsx

closed #217 
- KPI 페이지에서 회원 가입 수를 나타내는 기능을 개발했습니다.
- state와 똑같은 array를 반복해 선언하는 불필요한 코드를 삭제하고, state를 활용해 랜더링 했습니다.
-  Container 컴포넌트에서 회원수(명)을 나타내기 위해 조건부 함수를 추가했습니다.
- Container 컴포넌트에서 map함수를 사용할 때, 배열 비구조화 방식을 활용해 랜더링을 진행했습니다.

feat: 회원 수 기능 추가 및 코드 리팩토링

---

src/pages/NewPartyPage/Atom/CreateModal/index.jsx
src/pages/NewPartyPage/Promotion/index.tsx
src/pages/NewPartyPage/Reservation/index.jsx

closed #216 
- 프로모션 코드 입력 및 적용 창 개발
- 프로모션 코드 확인 및 적용 결과에 따른 모달창 제공
- 프로모션 코드 확인 결과에 따른 적용 버튼 비활성화/활성화
- 파티 생성 시 monopoly, promotionId값 추가
- 프로모션 코드
- 다루어야 할 여러 유저 이벤트가 더 있을 거 같은데, 우선 오늘까지 급한 기능 개발이 이루어져야 해서 PR 날립니다. 혹시, 테스트 해보시거나 코드 보시면서 더 보완해야 할 부분 있으면 알려주시면 감사하겠습니다. :)

feat: 프로모션 코드

---

src/pages/NewPartyPage/Promotion/index.tsx
src/pages/NewPartyPage/Reservation/index.jsx

- #216 
- 프로모션 코드 사용시 가격을 체크합니다.
- 15만원 이상 파티에서는 사용 불가능

프로모션 코드 가격 체크

---

src/pages/NewPartyPage/Reservation/index.jsx

- #216 
- 프로모션 코드 사용시 결제 수단 등록 없이 가입이 가능합니다.
- 코드 사용하면, 결제 수단 등록 컴포넌트를 숨김 처리합니다.

프로모션 코드 사용시 결제 수단 등록 패스

---

src/pages/NewPartyPage/Edit/index.jsx

- #216 
- 새로운 파티 만들기 코스 변경시에도 프로모션 적용이 가능하도록 처리했습니다.

새로운 파티 코스 변경 프로모션 적용 가능

---

src/pages/CommunityPage/ArticleDetail/ArticleBody/index.jsx

fix: 커뮤니티 내 하트(좋아요) 제거

---

src/api/driver.ts
src/components/Promotion/index.tsx
src/pages/LandingPage/UserMenu/index.tsx
src/pages/NewPartyPage/Region/index.tsx

- getDriver api에 토큰 여부 false 설정
- 랜딩 페이지에  "파티" 텍스트를 '여행'으로 변경
- 드라이버 프로필에서 코스 추가 + 버튼 클릭했을 때 지역이 안 보이는 현상 수정
- '적용하기' 버튼 단일화
- 사용할 수 있는 프로모션 코드일 경우 CheckModal 활성화, 아닐 경우 에러 메시지 ConfirmModal 활성화

프로모션 코드 UI UX 개선

---

src/pages/NewPartyPage/Atom/CreateModal/index.tsx
src/pages/PartyPage/JoinModal/index.tsx
src/pages/PartyPage/index.tsx
src/pages/SignupPage/Complete/index.tsx
src/types/global.d.ts
src/utils/naverTracking.ts

네이버 트래킹 스크립트 코드 작성

---

src/components/PassCheck/index.tsx
src/pages/SignupPage/index.tsx

- 웹뷰에서 `Pass 본인 인증` 팝업이 불가능한 상황 대응
- 페이지 리다이렉트로 처리

fix: Pass 본인 인증 로직 수정(팝업 대응)
